### ISSUE TITLE
code code plz

### ISSUE THREAD

**Issue by catwangyi** [fakufaku/auxiva-iss-dnn#2]

**Comment by fakufaku** [comment]
Hi @catwangyi , I apologize for the state of this repo! Actually, the code to train IVA-DNN models has been shared as part of the [torchiva](https://github.com/fakufaku/torchiva) package! I will add a re-direct in the readme!

**Comment by catwangyi** [comment]
Thx




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Robin ***@***.***&gt;; 
发送时间: 2022年11月10日(星期四) 晚上8:11
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [fakufaku/auxiva-iss-dnn] code code plz (Issue #2)





 
Hi @catwangyi , I apologize for the state of this repo! Actually, the code to train IVA-DNN models has been shared as part of the torchiva package! I will add a re-direct in the readme!
